global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus-internal'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - 'alert.rules.yml'
